config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create, :show]
  # resource :user rachel is sure.
  namespace :admin do
    resources :users
  end

  resources :articles

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :article_image, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :article_tags
  has_many :tags, through: :article_tags

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tag_string)
    tag_names = tag_string.split(",").collect{ |s| s.strip.capitalize }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(title: name) }
    self.tags = new_or_found_tags
  end
end

app/models/article_tag.rb
class ArticleTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags

  def to_s
    title
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true
  validates :password, presence: true
  has_many :articles
  enum role: %w(default admin)
  # has_many :authored_articles, class_name: "Article", foreign_key: "author_id"
  # has_many :likes
  # has_many :articles, through: :likes

  def owns?(article)
    self.id == article.user_id
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
 def show
   
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      # save_tags
      redirect_to @article
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      # save_tags
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    # byebug
    @article = Article.find(params[:id])
    tags = ArticleTag.where(article_id: params[:id])
    ArticleTag.destroy(tags)
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title,
                                    :body,
                                    :article_image,
                                    :tag_list)
  end

  def save_tags
    params[:article][:tags].split.each do |tag|
      @article.tags.find_or_create_by(title: tag.capitalize)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Logged in"
      if current_admin?
        redirect_to admin_user_path(@user)
      else
        redirect_to user_path(@user)
      end
    else
      flash.now[:alert] = "User name or password are invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account Created!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end


  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :image_path)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/show.html.erb
<h1> <%= current_user.name %> </h1>
<%= link_to "Log Out", logout_path, method: :delete %>

app/views/articles/edit.html.erb
<h1>Edit <%= @article.title %></h1>
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :article_image %>
  <%= f.text_field :article_image %>
  <br>

  <%= f.label :body %>
  <%= f.text_area :body  %>
  <br>

  <%= f.label :tag_list %>
  <%= f.text_field :tag_list, value: "" %>

  <%= f.submit "Complete" %>

<% end  %>

app/views/articles/index.html.erb
<h1>Article Index</h1>
<br>
<ul>
  <% @articles.each do |article| %>
  <li><%= link_to article.title, article %></li>
  Author: <%= article.user.name %>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1> Create a new Article</h1>
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :article_image %>
  <%= f.text_field :article_image %>
  <br>

  <%= f.label :body %>
  <%= f.text_area :body  %>
  <br>

  <%= f.label :tag_list %>
  <%= f.text_field :tag_list, value: "" %>

  <%= f.submit %>

<% end  %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<br>
<h2><%= @article.user.name %></h2>

<% @article.tags.each do |tag| %>
  <h3> <%= tag.title %> </h3>
<%#= Need to add link to tags  %>

<% end %>
<br>
<%= @article.article_image %>
<br>
<div class="body">
  <p>
    <%= @article.body %>
  </p>
</div>

<% if current_user.owns?(@article) %>
  <%= link_to "Edit", edit_article_path(@article) %>
  <%= link_to "Delete", article_path(@article), method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BonusLevel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "flash_#{type}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2> <%=  pluralize(target.errors.count, "error") %> prohibited this record from being saved: </h2>
  <ul>
    <% target.errors.full_messages.each do |message| %>
      <li> <%= message %>  </li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<%= form_for(@user) do |f| %>
  <%= render partial: "shared/errors", locals: { target: @user } %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= link_to "Home", current_user %>
<%= link_to "Log Out", logout_path, method: :delete %>



<h1> <%= current_user.name %> </h1>

<%= link_to "Create Article", new_article_path %>

app/views/welcome/index.html.erb
<h1>WELCOME!</h1>

<%= link_to "Create Account", new_user_path %>
<br>

<%= link_to "Login to Account", login_path %>